import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import LenisProvider from "@/components/provider/LenisProvider";
import { ChatWidget } from "@/components/chat/ChatWidget";
import { ChatProvider } from "@/context/ChatContext";
import { ChatWidgetWithContext } from "@/components/chat/ChatWidgetWithContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider>
          {children}
        </LenisProvider>
        <ChatWidget
          data-lenis-prevent
          title="Chat Support"
          subtitle="We typically reply within minutes"
          accentColor="#00bbff"
        />
      </body>
    </html>
  );
}
